default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: coderwall_development

test:
  <<: *default
  database: coderwall_test

production:
  <<: *default
  database: coderwall_production
